app/urls.py
from django.urls import path
from app.views import *
from app.views.administrador.views import *
from app.views.operador.views import *
from app.views.terminal.views import *
from app.views.area.views import *
from app.views.marca.views import *
from app.views.agente.views import *
from app.views.activo.views import *
from app.views.movimiento.views import *
from backups.views import BackupDatabaseView, RestoreDatabaseView, DeleteBackupView, BackupListView

app_name = 'app'
urlpatterns = [
    ### CRUD ADMINISTRADOR ###
    path('administrador/listar/', AdministradorListView.as_view(), name='administrador_lista'),
    path('administrador/crear/', AdministradorCreateView.as_view(), name='administrador_crear'),
    path('administrador/editar/<int:pk>/', AdministradorUpdateView.as_view(), name='administrador_editar'),
    path('administrador/eliminar/<int:pk>/', AdministradorDeleteView.as_view(), name='administrador_eliminar'),

    ### CRUD OPERADOR ###
    path('operador/listar/', OperadorListView.as_view(), name='operador_lista'),
    path('operador/crear/', OperadorCreateView.as_view(), name='operador_crear'),
    path('operador/editar/<int:pk>/', OperadorUpdateView.as_view(), name='operador_editar'),
    path('operador/eliminar/<int:pk>/', OperadorDeleteView.as_view(), name='operador_eliminar'),

    ### COPIA DE SEGURIDAD DE BASE DE DATOS ###
    path('gestionar_backups/', BackupDatabaseView.as_view(), name='gestionar_backups'),
    path('restaurar_backup/', RestoreDatabaseView.as_view(), name='restaurar_backup'),
    path('eliminar-backup/', DeleteBackupView.as_view(), name='eliminar_backup'),
    path('backup_list/', BackupListView.as_view(), name='backup_list'),

    ### CRUD TERMINAL ###
    path('terminal/listar/', TerminalListView.as_view(), name='terminal_lista'),
    path('terminal /crear/', TerminalCreateView.as_view(), name='terminal_crear'),
    path('terminal/editar/<int:pk>/', TerminalUpdateView.as_view(), name='terminal_editar'),
    path('terminal/eliminar/<int:pk>/', TerminalDeleteView.as_view(), name='terminal_eliminar'),

    ### CRUD AREA ###
    path('area/listar/', AreaListView.as_view(), name='area_lista'),
    path('area /crear/', AreaCreateView.as_view(), name='area_crear'),
    path('area/editar/<int:pk>/',AreaUpdateView.as_view(), name='area_editar'),
    path('area/eliminar/<int:pk>/', AreaDeleteView.as_view(), name='area_eliminar'),

    ### CRUD MARCA ###
    path('marca/listar/', MarcaListView.as_view(), name='marca_lista'),
    path('marca/crear/', MarcaCreateView.as_view(), name='marca_crear'),
    path('marca/editar/<int:pk>/', MarcaUpdateView.as_view(), name='marca_editar'),
    path('marca/eliminar/<int:pk>/', MarcaDeleteView.as_view(), name='marca_eliminar'),

    ### CRUD AGENTE ###
    path('agente/listar/', AgenteListView.as_view(), name='agente_lista'),
    path('agente/crear/', AgenteCreateView.as_view(), name='agente_crear'),
    path('agente/editar/<int:pk>/', AgenteUpdateView.as_view(), name='agente_editar'),
    path('agente/eliminar/<int:pk>/', AgenteDeleteView.as_view(), name='agente_eliminar'),

    ### CRUD ACTIVO ###
    path('activo/listar/', ActivoListView.as_view(), name='activo_lista'),
    path('activo/crear/', ActivoCreateView.as_view(), name='activo_crear'),
    path('activo/editar/<int:pk>/', ActivoUpdateView.as_view(), name='activo_editar'),
    path('activo/eliminar/<int:pk>/', ActivoDeleteView.as_view(), name='activo_eliminar'),

    ### CRUD MOVIMIENTO ###
    path('movimiento/listar/', MovimientoListView.as_view(), name='movimiento_lista'),
    path('movimiento/crear/', MovimientoCreateView.as_view(), name='movimiento_crear'),
    path('movimiento/editar/<int:pk>/', MovimientoUpdateView.as_view(), name='movimiento_editar'),
    path('movimiento/eliminar/<int:pk>/', MovimientoDeleteView.as_view(), name='movimiento_eliminar'),

    ### API'S ###
    path('movimiento/terminal_api/', TerminalAPI.as_view(), name='terminal_api'),
    path('movimiento/activo_api/', ActivoAPI.as_view(), name='activo_api'),
    path('movimiento/agente_api/', AgenteAPI.as_view(), name='agente_api'),
    path('movimiento/area_api/', AreaAPI.as_view(), name='area_api'),
]

coordistock/urls.py
from django.contrib import admin
from django.urls import path, include
from login.views import *
from app.views import *
from dashboard.views import *
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect

urlpatterns = [
    path('', include('login.urls')),
    path('dashboard', dashView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

app/views/operador/views.py
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.shortcuts import render
from django.core.exceptions import ValidationError
from django.http import JsonResponse
from app.models import Operador
from app.forms import OperadorForm
from django.db.models import ProtectedError

@method_decorator(login_required, name='dispatch')
class OperadorListView(ListView):
    model = Operador
    template_name = 'operador/listar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Listado de operadores'
        context['entidad'] = 'Listado de operadores'
        context['listar_url'] = reverse_lazy('app:operador_lista')
        context['crear_url'] = reverse_lazy('app:operador_crear')
        context['has_permission'] = self.request.user.has_perm('app.view_operador')

        if self.request.user.groups.filter(name='Operador').exists():
            context['can_add'] = False
        else:
            context['can_add'] = self.request.user.has_perm('app.add_operador')

        return context

@method_decorator(login_required, name='dispatch')
class OperadorCreateView(CreateView):
    model = Operador
    form_class = OperadorForm
    template_name = 'operador/crear.html'
    success_url = reverse_lazy('app:operador_lista')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Registrar operador'
        context['entidad'] = 'Registrar operador'
        context['listar_url'] = reverse_lazy('app:operador_lista')
        context['has_permission'] = not self.request.user.groups.filter(name='Operador').exists() and self.request.user.has_perm('app.add_operador')
        return context

    def form_valid(self, form):
        try:
            form.save()
            return JsonResponse({'success': True, 'message': 'Operador creado exitosamente.'})
        except ValidationError as e:
            form.add_error(None, e)
            return self.form_invalid(form)

    def form_invalid(self, form):
        errors = form.errors.as_json()
        return JsonResponse({'success': False, 'errors': errors})

@method_decorator(login_required, name='dispatch')
class OperadorUpdateView(UpdateView):
    model = Operador
    form_class = OperadorForm
    template_name = 'operador/crear.html'
    success_url = reverse_lazy('app:operador_lista')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Editar operador'
        context['entidad'] = 'Editar operador'
        context['listar_url'] = reverse_lazy('app:operador_lista')
        context['has_permission'] = not self.request.user.groups.filter(name='Operador').exists() and self.request.user.has_perm('app.change_operador')
        return context

    def form_valid(self, form):
        try:
            form.save()
            return JsonResponse({'success': True, 'message': 'Operador editado exitosamente.'})
        except ValidationError as e:
            form.add_error(None, e)
            return self.form_invalid(form)

    def form_invalid(self, form):
        errors = form.errors.as_json()
        return JsonResponse({'success': False, 'errors': errors})

@method_decorator(login_required, name='dispatch')
class OperadorDeleteView(DeleteView):
    model = Operador
    template_name = 'operador/eliminar.html'
    success_url = reverse_lazy('app:operador_lista')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Eliminar operador'
        context['entidad'] = 'Eliminar operador'
        context['listar_url'] = reverse_lazy('app:operador_lista')
        context['has_permission'] = not self.request.user.groups.filter(name='Operador').exists() and self.request.user.has_perm('app.delete_operador')
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            return JsonResponse({'success': True, 'message': 'Operador eliminado con éxito.'})
        except ProtectedError:
            return JsonResponse({'success': False, 'message': 'No se puede eliminar el operador.'})

app/templates/operador/crear.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% block contenido %}
<form method="post" action=".">
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-plus"></i>
                {{titulo}}
            </h3>
        </div>
        <div class="card-body">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="card-footer">
        <button class="btn btn-primary btn-flat"><i class="fas fa-plus"></i> Guardar</button>
        <a href="{{ listar_url }}" class="btn btn-danger btn-flat"><i class="fas fa-times"></i> Cancelar</a>
    </div>
</form>

<script>
    $(document).ready(function () {
        $('form').on('submit', function (event) {
            event.preventDefault(); 

            $.ajax({
                type: $(this).attr('method'),
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function (response) {
                    if (response.success) {
                        Swal.fire({
                            title: 'Éxito',
                            text: response.message,  
                            icon: 'success',
                            confirmButtonText: 'OK'
                        }).then(() => {
                            window.location.href = "{% url 'app:operador_lista' %}";
                        });
                    } else {
                        let errorMessages = '';
                        let errors = JSON.parse(response.errors);
                        for (let field in errors) {
                            for (let error of errors[field]) {
                                errorMessages += `${error.message}<br>`;
                            }
                        }

                        Swal.fire({
                            title: 'Error',
                            html: errorMessages,
                            icon: 'error',
                            confirmButtonText: 'Aceptar',
                            confirmButtonColor: '#4D90FE'
                        });
                    }
                }
            });
        });
    });
</script>
{% endblock %}

app/templates/operador/eliminar.html
{% extends 'eliminar.html' %}

app/templates/operador/listar.html
{% extends 'listar_no.html' %}

{% block columnas %}
<tr>
    <th scope="col">ID</th>
    <th scope="col">Nombre</th>
    <th scope="col">Tipo de documento</th>
    <th scope="col">Número de documento</th>
    <th scope="col">Email</th>
    <th scope="col">Teléfono</th>
    <th scope="col">Opciones</th>
</tr>
{% endblock %}

{% block filas %}
    {% if not has_permission %}
        <tr>
            <td colspan="7">
                <div class="alert alert-danger" role="alert">
                    No tienes permiso para ver esta información.
                </div>
            </td>
        </tr>
    {% else %}
        {% for o in object_list %}
        <tr>
            <td>{{ o.id }}</td>
            <td>{{ o.nombre }}</td>
            <td>{{ o.tipo_documento }}</td>
            <td>{{ o.numero_documento }}</td>
            <td>{{ o.user.email }}</td>
            <td>{{ o.telefono }}</td>
            <td>
                <a href="{% url 'app:operador_editar' o.id %}" class="btn btn-info btn-sm">
                    <i class="fas fa-edit"></i>
                </a>
                <a href="{% url 'app:operador_eliminar' o.id %}" class="btn btn-danger btn-sm">
                    <i class="fas fa-trash"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    {% endif %}
{% endblock %}
{% block javascript %}
<script type="application/javascript">
    $(document).ready(function () {
        $("#tabla").DataTable({
            responsive: true,
            initComplete: function () {
                var api = this.api();
                var columnNames = ['id', 'Nombre', 'Tipo de documento', 'Número de documento', 'Email', 'Teléfono', 'Opciones'];
                var excludedColumnIndex = columnNames.indexOf('Opciones'); 
                api.columns().every(function (index) {
                    var column = this;
                    var header = $(column.header());
                    if (index !== excludedColumnIndex) {
                        var filterContainer = $('<div class="filter-container"></div>').appendTo(header.empty());
                        $('<label>' + columnNames[index] + '</label>').appendTo(filterContainer);
                        var select = $('<select><option value="">Todos</option></select>')
                            .appendTo(filterContainer)
                            .on('change', function () {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );
                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });
                        column.data().unique().sort().each(function (d, j) {
                            select.append('<option value="' + d + '">' + d + '</option>');
                        });
                    } else {
                        $('<label>' + columnNames[index] + '</label>').appendTo(header.empty());
                    }
                });
            }
        });
    });
</script>
{% endblock %}