app/urls.py
from django.urls import path
from app.views import *
from app.views.administrador.views import *
from app.views.operador.views import *
from app.views.terminal.views import *
from app.views.area.views import *
from app.views.marca.views import *
from app.views.agente.views import *
from app.views.activo.views import *
from app.views.movimiento.views import *
from backups.views import BackupDatabaseView, RestoreDatabaseView, DeleteBackupView, BackupListView

app_name = 'app'
urlpatterns = [
    ### CRUD ADMINISTRADOR ###
    path('administrador/listar/', AdministradorListView.as_view(), name='administrador_lista'),
    path('administrador/crear/', AdministradorCreateView.as_view(), name='administrador_crear'),
    path('administrador/editar/<int:pk>/', AdministradorUpdateView.as_view(), name='administrador_editar'),
    path('administrador/eliminar/<int:pk>/', AdministradorDeleteView.as_view(), name='administrador_eliminar'),

    ### CRUD OPERADOR ###
    path('operador/listar/', OperadorListView.as_view(), name='operador_lista'),
    path('operador/crear/', OperadorCreateView.as_view(), name='operador_crear'),
    path('operador/editar/<int:pk>/', OperadorUpdateView.as_view(), name='operador_editar'),
    path('operador/eliminar/<int:pk>/', OperadorDeleteView.as_view(), name='operador_eliminar'),

    ### COPIA DE SEGURIDAD DE BASE DE DATOS ###
    path('gestionar_backups/', BackupDatabaseView.as_view(), name='gestionar_backups'),
    path('restaurar_backup/', RestoreDatabaseView.as_view(), name='restaurar_backup'),
    path('eliminar-backup/', DeleteBackupView.as_view(), name='eliminar_backup'),
    path('backup_list/', BackupListView.as_view(), name='backup_list'),

    ### CRUD TERMINAL ###
    path('terminal/listar/', TerminalListView.as_view(), name='terminal_lista'),
    path('terminal /crear/', TerminalCreateView.as_view(), name='terminal_crear'),
    path('terminal/editar/<int:pk>/', TerminalUpdateView.as_view(), name='terminal_editar'),
    path('terminal/eliminar/<int:pk>/', TerminalDeleteView.as_view(), name='terminal_eliminar'),

    ### CRUD AREA ###
    path('area/listar/', AreaListView.as_view(), name='area_lista'),
    path('area /crear/', AreaCreateView.as_view(), name='area_crear'),
    path('area/editar/<int:pk>/',AreaUpdateView.as_view(), name='area_editar'),
    path('area/eliminar/<int:pk>/', AreaDeleteView.as_view(), name='area_eliminar'),

    ### CRUD MARCA ###
    path('marca/listar/', MarcaListView.as_view(), name='marca_lista'),
    path('marca/crear/', MarcaCreateView.as_view(), name='marca_crear'),
    path('marca/editar/<int:pk>/', MarcaUpdateView.as_view(), name='marca_editar'),
    path('marca/eliminar/<int:pk>/', MarcaDeleteView.as_view(), name='marca_eliminar'),

    ### CRUD AGENTE ###
    path('agente/listar/', AgenteListView.as_view(), name='agente_lista'),
    path('agente/crear/', AgenteCreateView.as_view(), name='agente_crear'),
    path('agente/editar/<int:pk>/', AgenteUpdateView.as_view(), name='agente_editar'),
    path('agente/eliminar/<int:pk>/', AgenteDeleteView.as_view(), name='agente_eliminar'),

    ### CRUD ACTIVO ###
    path('activo/listar/', ActivoListView.as_view(), name='activo_lista'),
    path('activo/crear/', ActivoCreateView.as_view(), name='activo_crear'),
    path('activo/editar/<int:pk>/', ActivoUpdateView.as_view(), name='activo_editar'),
    path('activo/eliminar/<int:pk>/', ActivoDeleteView.as_view(), name='activo_eliminar'),

    ### CRUD MOVIMIENTO ###
    path('movimiento/listar/', MovimientoListView.as_view(), name='movimiento_lista'),
    path('movimiento/crear/', MovimientoCreateView.as_view(), name='movimiento_crear'),
    path('movimiento/editar/<int:pk>/', MovimientoUpdateView.as_view(), name='movimiento_editar'),
    path('movimiento/eliminar/<int:pk>/', MovimientoDeleteView.as_view(), name='movimiento_eliminar'),

    ### API'S ###
    path('movimiento/terminal_api/', TerminalAPI.as_view(), name='terminal_api'),
    path('movimiento/activo_api/', ActivoAPI.as_view(), name='activo_api'),
    path('movimiento/agente_api/', AgenteAPI.as_view(), name='agente_api'),
    path('movimiento/area_api/', AreaAPI.as_view(), name='area_api'),
]

coordistock/urls.py
from django.contrib import admin
from django.urls import path, include
from login.views import *
from app.views import *
from dashboard.views import *
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect

urlpatterns = [
    path('', include('login.urls')),
    path('dashboard', dashView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

app/views/terminal/views.py
from django.contrib import messages
import django
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
import os
from django.urls import reverse_lazy, reverse
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
from django.db.models import ProtectedError
from app.models import Terminal
from app.forms import TerminalForm

@method_decorator(never_cache, name='dispatch')
def lista_terminal(request):
    nombre = {
        'titulo': 'Listado de terminales',
        'terminales': Terminal.objects.all()
    }
    return render(request, 'terminal/listar.html',nombre)

###### LISTAR ######

@method_decorator(never_cache, name='dispatch')
class TerminalListView(ListView):
    model = Terminal
    template_name = 'terminal/listar.html'
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        nombre = {'nombre': 'Juan'}
        return JsonResponse(nombre)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Listado de terminales'
        context['entidad'] = 'Listado de terminales'
        context['listar_url'] = reverse_lazy('app:terminal_lista')
        context['crear_url'] = reverse_lazy('app:terminal_crear')
        return context

###### CREAR ######
@method_decorator(never_cache, name='dispatch')
class TerminalCreateView(CreateView):
    model = Terminal
    form_class = TerminalForm
    template_name = 'terminal/crear.html'
    success_url = reverse_lazy('app:terminal_lista')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Registrar terminal'
        context['entidad'] = 'Registrar terminal'
        context['listar_url'] = reverse_lazy('app:terminal_lista')
        return context
    
    def form_valid(self, form):
        terminal = form.cleaned_data.get('terminal').lower()
        
        if Terminal.objects.filter(terminal__iexact=terminal).exists():
            form.add_error('terminal', 'Ya existe una terminal registrada con ese nombre.')
            return self.form_invalid(form)
        
        response = super().form_valid(form)
        success_url = reverse('app:terminal_crear') + '?created=True'
        return redirect(success_url)

###### EDITAR ######

@method_decorator(never_cache, name='dispatch')
class TerminalUpdateView(UpdateView):
    model = Terminal
    form_class = TerminalForm
    template_name = 'terminal/crear.html'
    success_url = reverse_lazy('app:terminal_lista')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Editar terminal'
        context['entidad'] = 'Editar terminal'
        context['error'] = 'Esta terminal ya existe'
        context['listar_url'] = reverse_lazy('app:terminal_lista')
        return context

    def form_valid(self, form):
        terminal = form.cleaned_data.get('terminal').lower()
        response = super().form_valid(form)
        success_url = reverse('app:terminal_crear') + '?updated=True'
        return redirect(success_url)

###### ELIMINAR ######

@method_decorator(never_cache, name='dispatch')
class TerminalDeleteView(DeleteView):
    model = Terminal
    template_name = 'terminal/eliminar.html'
    success_url = reverse_lazy('app:terminal_lista')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Eliminar terminal'
        context['entidad'] = 'Eliminar terminal'
        context['listar_url'] = reverse_lazy('app:terminal_lista')
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            return JsonResponse({'success': True, 'message': 'Terminal eliminada con éxito.'})
        except ProtectedError:
            return JsonResponse({'success': False, 'message': 'No se puede eliminar la terminal.'})

app/templates/terminal/crear.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% block contenido %}
<form method="post" action=".">
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-plus"></i>
                {{titulo}}
            </h3>
        </div>
        <div class="card-body">
            {% csrf_token %}
            {% for field in form.visible_fields %}
            <div class="form-group">
                <label for="text">{{ field.label }}:</label>
                {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="card-footer">
        <button class="btn btn-primary btn-flat"><i class="fas fa-plus"></i> Guardar</button>
        <a href="{{ listar_url }}" class="btn btn-danger btn-flat">
            <i class="fas fa-times"></i> Cancelar
        </a>
    </div>
    </div>
</form>
<script>
    {% if form.errors %}
    var errors = '';
    {% for field in form %}
    {% for error in field.errors %}
    errors += '{{ error }}';
    {% endfor %}
    {% endfor %}

    Swal.fire({
        title: 'Error',
        text: 'Ya existe una terminal con este nombre.',
        icon: 'error',
        confirmButtonText: 'Aceptar',
        confirmButtonColor: '#4D90FE'
    });
    {% elif request.GET.created %}
    Swal.fire({
        title: 'Éxito',
        text: 'Terminal registrada con éxito.',
        icon: 'success',
        confirmButtonText: 'Aceptar',
        confirmButtonColor: '#4D90FE'
    }).then((result) => {
        if (result.isConfirmed) {
            window.location.href = "{% url 'app:terminal_lista' %}";
        }
    });
    {% elif request.GET.updated %}
    Swal.fire({
        title: 'Éxito',
        text: 'Terminal editada con éxito.',
        icon: 'success',
        confirmButtonText: 'Aceptar',
        confirmButtonColor: '#4D90FE'
    }).then((result) => {
        if (result.isConfirmed) {
            window.location.href = "{% url 'app:terminal_lista' %}";
        }
    });
    {% endif %}
</script>
{% endblock %}

app/templates/terminal/listar.html
{% extends 'listar.html' %}

{% block columnas %}
<tr>
    <th scope="col">id</th>
    <th scope="col">Terminal</a></th>
    <th scope="col">Ciudad</th>
    <th scope="col">Direccion</th>
    <th scope="col">Estado</th>
    <th scope="col">Opciones</th>
</tr>
{% endblock %}

{% block filas %}
{% for t in object_list %}
<tr>
    <td>{{ t.id }}</td>
    <td>{{ t.terminal }}</td>
    <td>{{ t.ciudad }}</td>
    <td>{{ t.direccion }}</td>
    <td>{{ t.estado | yesno:"Activo,Inactivo" }}</td>
    <td>
        <a href="{% url 'app:terminal_editar' t.id %}" class="btn btn-info btn-sm"><i class="fas fa-edit"></i></a>
        <a href="{% url 'app:terminal_eliminar' t.id %}" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></a>
    </td>
</tr>
{% endfor %}
{% endblock %}
{% block javascript %}
<script type="application/javascript">
    $(document).ready(function () {
        $("#tabla").DataTable({
            responsive: true,
            initComplete: function () {
                var api = this.api();
                var columnNames = ['id', 'Terminal', 'Ciudad', 'Direccion', 'Estado', 'Opciones'];
                var excludedColumnIndex = columnNames.indexOf('Opciones');
                api.columns().every(function (index) {
                    var column = this;
                    var header = $(column.header());
                    if (index !== excludedColumnIndex) {
                        var filterContainer = $('<div class="filter-container"></div>').appendTo(header.empty());
                        $('<label>' + columnNames[index] + '</label>').appendTo(filterContainer);
                        var select = $('<select><option value="">Todos</option></select>')
                            .appendTo(filterContainer)
                            .on('change', function () {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );
                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });
                        column.data().unique().sort().each(function (d, j) {
                            select.append('<option value="' + d + '">' + d + '</option>');
                        });
                    } else {
                        $('<label>' + columnNames[index] + '</label>').appendTo(header.empty());
                    }
                });
            }
        });
    });
</script>
{% endblock %}