app/urls.py
from django.urls import path
from app.views import *
from app.views.administrador.views import *
from app.views.operador.views import *
from app.views.terminal.views import *
from app.views.area.views import *
from app.views.marca.views import *
from app.views.agente.views import *
from app.views.activo.views import *
from app.views.movimiento.views import *
from backups.views import BackupDatabaseView, RestoreDatabaseView, DeleteBackupView, BackupListView

app_name = 'app'
urlpatterns = [
    ### CRUD ADMINISTRADOR ###
    path('administrador/listar/', AdministradorListView.as_view(), name='administrador_lista'),
    path('administrador/crear/', AdministradorCreateView.as_view(), name='administrador_crear'),
    path('administrador/editar/<int:pk>/', AdministradorUpdateView.as_view(), name='administrador_editar'),
    path('administrador/eliminar/<int:pk>/', AdministradorDeleteView.as_view(), name='administrador_eliminar'),

    ### CRUD OPERADOR ###
    path('operador/listar/', OperadorListView.as_view(), name='operador_lista'),
    path('operador/crear/', OperadorCreateView.as_view(), name='operador_crear'),
    path('operador/editar/<int:pk>/', OperadorUpdateView.as_view(), name='operador_editar'),
    path('operador/eliminar/<int:pk>/', OperadorDeleteView.as_view(), name='operador_eliminar'),

    ### COPIA DE SEGURIDAD DE BASE DE DATOS ###
    path('gestionar_backups/', BackupDatabaseView.as_view(), name='gestionar_backups'),
    path('restaurar_backup/', RestoreDatabaseView.as_view(), name='restaurar_backup'),
    path('eliminar-backup/', DeleteBackupView.as_view(), name='eliminar_backup'),
    path('backup_list/', BackupListView.as_view(), name='backup_list'),

    ### CRUD TERMINAL ###
    path('terminal/listar/', TerminalListView.as_view(), name='terminal_lista'),
    path('terminal /crear/', TerminalCreateView.as_view(), name='terminal_crear'),
    path('terminal/editar/<int:pk>/', TerminalUpdateView.as_view(), name='terminal_editar'),
    path('terminal/eliminar/<int:pk>/', TerminalDeleteView.as_view(), name='terminal_eliminar'),

    ### CRUD AREA ###
    path('area/listar/', AreaListView.as_view(), name='area_lista'),
    path('area /crear/', AreaCreateView.as_view(), name='area_crear'),
    path('area/editar/<int:pk>/',AreaUpdateView.as_view(), name='area_editar'),
    path('area/eliminar/<int:pk>/', AreaDeleteView.as_view(), name='area_eliminar'),

    ### CRUD MARCA ###
    path('marca/listar/', MarcaListView.as_view(), name='marca_lista'),
    path('marca/crear/', MarcaCreateView.as_view(), name='marca_crear'),
    path('marca/editar/<int:pk>/', MarcaUpdateView.as_view(), name='marca_editar'),
    path('marca/eliminar/<int:pk>/', MarcaDeleteView.as_view(), name='marca_eliminar'),

    ### CRUD AGENTE ###
    path('agente/listar/', AgenteListView.as_view(), name='agente_lista'),
    path('agente/crear/', AgenteCreateView.as_view(), name='agente_crear'),
    path('agente/editar/<int:pk>/', AgenteUpdateView.as_view(), name='agente_editar'),
    path('agente/eliminar/<int:pk>/', AgenteDeleteView.as_view(), name='agente_eliminar'),

    ### CRUD ACTIVO ###
    path('activo/listar/', ActivoListView.as_view(), name='activo_lista'),
    path('activo/crear/', ActivoCreateView.as_view(), name='activo_crear'),
    path('activo/editar/<int:pk>/', ActivoUpdateView.as_view(), name='activo_editar'),
    path('activo/eliminar/<int:pk>/', ActivoDeleteView.as_view(), name='activo_eliminar'),

    ### CRUD MOVIMIENTO ###
    path('movimiento/listar/', MovimientoListView.as_view(), name='movimiento_lista'),
    path('movimiento/crear/', MovimientoCreateView.as_view(), name='movimiento_crear'),
    path('movimiento/editar/<int:pk>/', MovimientoUpdateView.as_view(), name='movimiento_editar'),
    path('movimiento/eliminar/<int:pk>/', MovimientoDeleteView.as_view(), name='movimiento_eliminar'),

    ### API'S ###
    path('movimiento/terminal_api/', TerminalAPI.as_view(), name='terminal_api'),
    path('movimiento/activo_api/', ActivoAPI.as_view(), name='activo_api'),
    path('movimiento/agente_api/', AgenteAPI.as_view(), name='agente_api'),
    path('movimiento/area_api/', AreaAPI.as_view(), name='area_api'),
]

coordistock/urls.py
from django.contrib import admin
from django.urls import path, include
from login.views import *
from app.views import *
from dashboard.views import *
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect

urlpatterns = [
    path('', include('login.urls')),
    path('dashboard', dashView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

app/templates/aside/body.html
{% extends 'home.html' %}
{% load static %}
{% block body %}

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper" style="display: grid; grid-template-rows: auto 1fr">
        {% include 'aside/header.html' %}
        {% include 'aside/sidebar.html' %}
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Inicio</a></li>
                                <li class="breadcrumb-item"><a href="{{listar_url}}">{{entidad}}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block contenido %}
                    {% endblock %}
                </div>
            </div>
        </div>
        {% include 'footer.html' %}
    </div>
    {% block javascript %}
    {% endblock %}
</body>
{% endblock %}

app/templates/aside/header.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-dark navbar-green">
    <ul class="navbar-nav">
        <li class="nav-itemmm">
            <a class="nav-link" id="toggle-menu" data-widget="pushmenu" href="#" role="button">
                <i class="fas fa-bars" style="color: white; font-size: 30px; text-shadow: 3px 3px 2.5px black;"></i>
            </a>
        </li>
        <li class="nav-itemmm d-none d-sm-inline-block ">
            <a href="{% url 'dashboard' %}" class="nav-link text-white"
                style="font-size: 20px; font-style: oblique; text-shadow: 3px 3px 2.5px black;">Inicio</a>
        </li>
    </ul>
    <div class="container">
        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
        </div>
    </div>
    <span class="icon" id="logo">
        <img src="{% static 'img/icon.png' %}" alt="Logo palmera">
    </span>
    <div class="col-sm-6">
        <h1 class="m-0" style="font-size: 50px; font-style: oblique; color: white; text-shadow: 3px 3px 2.5px black;">Panel de administración</h1>
    </div>
    <ul class="navbar-nav ml-auto">
        <li class="nav-itemmm">
            <a class="nav-link" href="">
                <i id="darkModeToggle" class="fas fa-moon" title="Modo oscuro-claro"
                    style="font-size: 30px; color: white; text-shadow: 3px 3px 2.5px black;" aria-hidden="true"
                    onclick="toggleDarkMode()"></i>
            </a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-itemmm">
            <a class="nav-link" href="{% static 'resources/Manual de usuario (Software G&V Asuán).pdf' %}" target="_blank">
                <i class="fas fa-question" title="Ayuda"
                    style="font-size: 30px; color: white; text-shadow: 3px 3px 2.5px black;" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
    {% if perms.app.view_usuario %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-itemmm">
            <a class="nav-link" href="{% url 'app:gestionar_backups'%}">
                <i class="fas fa-database" title="Administrar copias de seguridad"
                    style="font-size: 30px; color: white; text-shadow: 3px 3px 2.5px black;" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
    {% endif %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-itemmm dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user" style="font-size: 30px; color: white; text-shadow: 3px 3px 2.5px black;"></i>
            </a>
            <div class="logout-menu dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <span class="dropdown-item" style="color: white">Usuario activo:<br>{{ user.username }}</span>
                <a class="dropdown-item" style="color: white" href="#" onclick="confirmLogout(event)">Cerrar sesión</a>
            </div>
        </li>
    </ul>
</nav>
<script src="{% static 'lib/sweetalert2/sweetHeader.js' %}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        function toggleDarkMode() {
            document.body.classList.toggle('dark-mode');
            const isDarkMode = document.body.classList.contains('dark-mode');
            const darkModeIcon = document.getElementById("darkModeToggle");

            localStorage.setItem('dark-mode', isDarkMode);

            if (isDarkMode) {
                darkModeIcon.classList.remove('fa-moon');
                darkModeIcon.classList.add('fa-sun');
            } else {
                darkModeIcon.classList.remove('fa-sun');
                darkModeIcon.classList.add('fa-moon');
            }
        }
        if (localStorage.getItem('dark-mode') === 'true') {
            document.body.classList.add('dark-mode');
            const darkModeIcon = document.getElementById("darkModeToggle");
            darkModeIcon.classList.remove('fa-moon');
            darkModeIcon.classList.add('fa-sun');
        }
        window.toggleDarkMode = toggleDarkMode;
    });

    function confirmLogout(event) {
        event.preventDefault();
        Swal.fire({
            title: '¿Desea cerrar sesión?',
            text: "",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#4D90FE',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sí, cerrar sesión',
            cancelButtonText: 'Cancelar'
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = "{% url 'logout' %}";
            }
        });
    }
</script>

app/templates/aside/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-collapse elevation-2">
    <div class="sidebar">
        <div class="logo-container text-center">
            <img src="{% static 'img/logo_coordistock.png' %}"  alt="Logo Asuán" class="logo-image img-fluid">
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" role="menu" data-accordion="false">
                <h1 style="font-size: 50px; font-style: oblique; color: white; text-align: center">ㅤ</h1>
                <li class="nav-itemm">
                    <a href="#submenu1" class="nav-link d-flex justify-content-between align-items-center"
                        data-toggle="collapse" aria-expanded="false" style="color: white; font-size: 13px;">
                        <div class="d-flex align-items-center">
                            <i class="nav-icon fas fa-tools" style="font-size: 25px; margin-right: 10px;"></i>
                            <p class="mb-0" style="font-size: 19px;">Acciones</p>
                        </div>
                    </a>
                    <ul class="collapse list-unstyled pl-4" id="submenu1">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:movimiento_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-exchange-alt" style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Realizar movimiento</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-itemm">
                    <a href="#submenu2" class="nav-link d-flex justify-content-between align-items-center"
                        data-toggle="collapse" aria-expanded="false" style="color: white; font-size: 13px;">
                        <div class="d-flex align-items-center">
                            <i class="nav-icon fas fa-dolly" style="font-size: 25px; margin-right: 10px;"></i>
                            <p class="mb-0" style="font-size: 19px;">Activos</p>
                        </div>
                    </a>
                    <ul class="collapse list-unstyled pl-4" id="submenu2">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:activo_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon nav-icon fas fa-code-branch"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Trazabilidad de activos</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:activo_crear' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-plus"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Registrar activo</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:marca_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-project-diagram"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Marcas</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-itemm">
                    <a href="#submenu3" class="nav-link d-flex justify-content-between align-items-center"
                        data-toggle="collapse" aria-expanded="false" style="color: white; font-size: 13px;">
                        <div class="d-flex align-items-center">
                            <i class="nav-icon fas fa-building" style="font-size: 25px; margin-right: 10px;"></i>
                            <p class="mb-0" style="font-size: 19px;">Distribución</p>
                        </div>
                    </a>
                    <ul class="collapse list-unstyled pl-4" id="submenu3">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:terminal_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon far fa-building"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Listado de terminales</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:area_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-list"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Listado de areas</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-itemm">
                    <a href="#submenu4" class="nav-link d-flex justify-content-between align-items-center"
                        data-toggle="collapse" aria-expanded="false" style="color: white; font-size: 13px;">
                        <div class="d-flex align-items-center">
                            <i class="nav-icon fas fa-user-friends" style="font-size: 25px; margin-right: 10px;"></i>
                            <p class="mb-0" style="font-size: 19px;">Gestión de agentes</p>
                        </div>
                    </a>
                    <ul class="collapse list-unstyled pl-4" id="submenu4">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:agente_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-list"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Lista de agentes</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:agente_crear' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-plus"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Registrar agente</span>
                            </a>
                        </li>
                    </ul>
                </li>
                {% if perms.app.view_usuario %}
                <li class="nav-itemm">
                    <a href="#submenu5" class="nav-link d-flex justify-content-between align-items-center"
                        data-toggle="collapse" aria-expanded="false" style="color: white; font-size: 13px;">
                        <div class="d-flex align-items-center">
                            <i class="nav-icon fas fa-user-cog" style="font-size: 25px; margin-right: 10px;"></i>
                            <p class="mb-0" style="font-size: 19px;">Gestión de usuarios</p>
                        </div>
                    </a>
                    <ul class="collapse list-unstyled pl-" id="submenu5">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:administrador_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-user-shield"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Administradores</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:operador_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-user-alt"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Operadores</span>
                            </a>
                        </li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</aside>
<script>
    $(document).ready(function () {
        $("#toggle-menu").click(function (e) {
            e.preventDefault();
            $(".logo-image").toggle();
        });
    });
    function delayCollapse(id) {
        setTimeout(function () {
            $(id).collapse('hide');
        }, 3000);
    }    
</script>